### ISSUE TITLE
rcutils package in CMakeLists.txt was badly written in ament_target_dependencies() l.38

### ISSUE THREAD

**Issue by wsuter96** [OPT4SMART/ros2-vicon-receiver#1]
l.38 ament_target_dependencies(vicon_client "rclcpp" "rclutils")
should be
l.38 ament_target_dependencies(vicon_client "rclcpp" "rcutils")
with this "fix" the package can be built...

**Comment by andrea-testa** [comment]
Thank you, we fixed the file.
