### ISSUE TITLE
Publishing position data in real time

### ISSUE THREAD

**Issue by CowboyJimie** [OPT4SMART/ros2-vicon-receiver#4]
The publisher of a created segment publish position's data of the segment (translation and rotation) only during the record's playing, namely after a motion is recorded, activated pipeline KinematicFit in Nexus for the segment and the record is playing.
During the real time (not a recorderded data), the publisher publish zero value both for translation and rotation for each axis and quaternions, even though the segment is in the scene and it is moving.

Is there any possibility to use this code in real time without capturing motion?

**Comment by andrea-testa** [comment]
Hi, this code is currently based on the Tracker software. We currently do not give support to Nexus. However, if you have any hint on this feel free to open a pull request!
Thank you for being so interested!
